services:
  - type: web
    name: roni-sardar
    runtime: node
    plan: free
    region: singapore
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: RESEND_SENDER_EMAIL
        value: backup@roni.kodl.uk
      - key: RESEND_DOMAIN
        value: roni.kodl.uk
